name: "Setup Axiom"
description: "Start a local Axiom deployment, set it up and create a personal token."
author: "Axiom"
branding:
  color: purple
  icon: x
inputs:
  axiom-version:
    description: "The Axiom version to use"
    default: "1.20.1"
    required: false
  axiom-port:
    description: "The port to run Axiom on"
    default: "8080"
    required: false
  axiom-license:
    description: "The license to run Axiom on"
    required: false
  axiom-db-image:
    description: "The Docker image to for the DB"
    default: "axiomhq/axiom-db"
    required: false
  axiom-core-image:
    description: "The Docker image to for Core"
    default: "axiomhq/axiom-core"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
